### ISSUE TITLE
Do i miss something? web local storage still doesnt work

### ISSUE THREAD

**Issue by ariebrainware** [ariebrainware/javascript-challenge1#2]
https://github.com/ariebrainware/javascript-challenge1/blob/17478e22a76bb61211b8d30671e87e671f52aba8/address-book/index.js#L1-L56

@mhaidarh @michaeltamsil

**Comment by michaeltamsil** [comment]
first of all you don't include `index.js` in `index.html` after that it have other issue about having bad syntax

https://github.com/ariebrainware/javascript-challenge1/blob/17478e22a76bb61211b8d30671e87e671f52aba8/address-book/index.html#L95-L102

**Comment by michaeltamsil** [comment]
also addToDOM function is not called "i'm testing it now"

**Comment by ariebrainware** [comment]
https://github.com/ariebrainware/javascript-challenge1/blob/212b6aab162e961629792104b0c67eb5da853e44/address-book/index.js#L21-L41

browser said, address is undefined, but i already define const
![screenshot from 2018-07-25 16-55-26](https://user-images.githubusercontent.com/26453961/43193994-92b8f988-902b-11e8-9ca0-d520459a5369.png)

**Comment by mhaidarhanif** [comment]
Shift the position of value getter into the `submit` event
